# Generated by Django 4.2 on 2025-11-16 02:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('all', 'All GitHub'), ('org', 'Organization'), ('repo', 'Repository'), ('tag', 'Tag'), ('custom', 'Custom List')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('star', 'Star'), ('fork', 'Fork'), ('pull_request', 'Pull Request'), ('commit', 'Commit'), ('release', 'Release'), ('issue', 'Issue'), ('watch', 'Watch')], max_length=20)),
                ('repository', models.CharField(max_length=500)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('actor_avatar', models.URLField(blank=True)),
                ('event_data', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sportscaster.channel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='sportscaster.githubevent')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='sportscaster.channel')),
            ],
            options={
                'unique_together': {('channel', 'entity_name')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=500)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('pull_requests', models.IntegerField(default=0)),
                ('commits', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='sportscaster.channel')),
            ],
            options={
                'ordering': ['-stars', '-forks'],
                'unique_together': {('channel', 'repository')},
            },
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['-timestamp', 'channel'], name='sportscaste_timesta_7057f0_idx'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['processed'], name='sportscaste_process_41a1e3_idx'),
        ),
    ]
